
start_block: 22606143            # June 1st 2025
end_block: 22829343              # June 30th 2025
#end_block: 23264566              # August 31st 2025
batch_size: 100

token:
  # eth special case - do not change
  - name: ETH
    address: "ethereum"
    active: True
    decimals: 18
  - name: USDT
    address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    active: True
    decimals: 6
  - name: USDC
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    active: True
    decimals: 6
  - name: WBTC
    address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
    active: True
    decimals: 8
  - name: USDE
    address: "0x4c9EDD5852cd905f086C759E8383e09bff1E68B3"
    active: True
    decimals: 18
  - name: CBBTC
    address: "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
    active: True
    decimals: 8

dex_events:
   #uniswao v3
  - "Swap(address,address,int256,int256,uint160,uint128,int24)"
  # Curve Finance
  - "TokenExchange(address,int128,uint256,int128,uint256)"
  - "TokenExchangeUnderlying(address,int128,uint256,int128,uint256)"
  # Balancer V2 (Vault)
  - "Swap(bytes32,address,address,uint256,uint256)"
  # Fluid
  - "Swap(address,address,int256,int256,uint256,uint128,int24)"

analysis:
  cumulative_wealth_gain:
    - 8
    - 16
    - 32
    - 7200
    - 50400
  transaction_counting:
    - 8
    - 16
    - 32
    - 7200
    - 50400
